traefik:
  image: emilevauge/traefik:latest
  labels:
    traefik.frontend.value: 'traefik.${DOMAIN}'
    traefik.frontend.passHostHeader: 'true'
    traefik.frontend.rule: 'Host'
    traefik.port: '8080'
  ports:
  - 80:80/tcp
  - 443:443/tcp
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - ${TRAEFIK_DIR}/traefik.toml:/traefik.toml
  log_opt:
    max-size: '50m'
  restart: 'no'
  read_only: true
  cpu_shares: 256
  mem_limit: 134217728