version: '2'

services:
  traefik:
    image: traefik
    command: -c /dev/null --defaultentrypoints=http --entryPoints='Name:http Address::80' --docker --docker.domain=${DOMAIN}
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: traefik.${DOMAIN}'
      traefik.port: '8080'
    ports:
    - 80:80/tcp
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: 'no'
    read_only: true

networks:
  default:
    external:
      name: traefik
