version: '2'

services:
  traefik:
    image: traefik
    command: -c /dev/null --web --web.readOnly --docker --docker.domain=${DOMAIN} --docker.endpoint tcp://${SWARM_IP}:2375 --docker.tls --docker.tls.ca /ssl/ca.pem --docker.tls.cert /ssl/cert.pem --docker.tls.key /ssl/key.pem --docker.tls.insecureSkipVerify
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: traefik.${DOMAIN}'
      traefik.port: '8080'
    ports:
    - 80:80/tcp
    volumes:
    - ${CERT_PATH}:/ssl
    logging:
      driver: json
      options:
        max-size: '50m'
    restart: 'no'
    read_only: true
    cpu_shares: 256
    mem_limit: 134217728

networks:
  default:
    external:
      name: swarm-net