version: '2'

services:
  traefik:
    image: traefik
    command: -c /conf/traefik.toml --web --web.readOnly --docker --docker.domain=${DOMAIN} --docker.endpoint tcp://${DOCKER_HOST} --docker.tls --docker.tls.ca /ssl/ca.pem --docker.tls.cert /ssl/cert.pem --docker.tls.key /ssl/key.pem --docker.tls.insecureSkipVerify
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: traefik.${DOMAIN}'
      traefik.port: '8080'
    environment:
    - affinity:container==swarm_manager
    ports:
    - 80:80/tcp
    - 443:443/tcp
    volumes:
    - ${DOCKER_CERT_PATH}:/ssl
    - ${TRAEFIK_CONF_DIR}:/conf
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: 'no'
    read_only: true

networks:
  default:
    external:
      name: swarm-net
