version: '2'

services:
  traefik:
    image: traefik:reblochon
    hostname: traefik
    command: -c /dev/null --defaultentrypoints=http --entryPoints='Name:http Address::80' --docker --docker.domain=${DOMAIN}
    labels:
      traefik.enable: 'false'
    ports:
    - 80:80/tcp
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 256
    mem_limit: 268435456
    security_opt:
    - no-new-privileges

networks:
  default:
    external:
      name: traefik
