port = ":80"

[web]
address = ":8080"

[docker]
domain = "vibioh.fr"
endpoint = "unix:///var/run/docker.sock"
watch = true

[acme]
email = "vincent.boutour@gmail.com"
storageFile = "acme.json"
entryPoint = "https"
onDemand = true